<?php

class Animal{
    private string $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function __toString():string
    {
           return "Animal[name=".$this->name."]";// TODO: Implement __toString() method.
    }
}

class Mammal extends Animal{
    public function __construct($name)
    {
        parent::__construct($name);
    }

    public function __toString():string
    {
        return "Mammal[".parent::__toString()."]";// TODO: Change the autogenerated stub
    }
}

class Cat extends Mammal{
    public function __construct($name)
    {
        parent::__construct($name);
    }

    public function greets():void
    {
        echo "Meow";
    }

    public function __toString():string
    {

        return "Cat[".parent::__toString()."]";// TODO: Change the autogenerated stub
    }
}

class Dog extends Mammal{
    public function __construct($name)
    {
        parent::__construct($name);
    }

    public function greets($sound = "Woof"):void
    {
        echo $sound;
    }

    public function __toString():string
    {
        // TODO: Change the autogenerated stub
        return "Dog[".parent::__toString()."]";
    }

}

$animalTest = new Animal("Tiger");

echo $animalTest.PHP_EOL;

$mammalTest = new Mammal("Panther");

echo $mammalTest.PHP_EOL;

$catTest = new Cat("Persian");

echo $catTest.PHP_EOL;

$dogTest = new Dog("Dalmation");

echo $dogTest.PHP_EOL;

$catTest->greets();

echo PHP_EOL;

$dogTest->greets();

echo PHP_EOL;

$dogTest->greets("Wooof");
