<?php

declare(strict_types=1);
class Person
{
    private string $name;
    private string $address;

    public function __construct(string $name, string $address)
    {
        $this->name = $name;
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    public function __toString():string
    {
        // TODO: Implement __toString() method.
        return "Person[name=".$this->name.", address=".$this->address."]";
    }


}

class Student extends Person{
    private string $program;
    private int $year;
    private float $fee;

    public function __construct(string $name, string $address, string $program, int $year, float $fee)
    {
        parent::__construct($name, $address);
        $this->program = $program;
        $this->year = $year;
        $this->fee = $fee;
    }

    /**
     * @return string
     */
    public function getProgram(): string
    {
        return $this->program;
    }

    /**
     * @param string $program
     */
    public function setProgram(string $program): void
    {
        $this->program = $program;
    }

    /**
     * @return int
     */
    public function getYear(): int
    {
        return $this->year;
    }

    /**
     * @param int $year
     */
    public function setYear(int $year): void
    {
        $this->year = $year;
    }

    /**
     * @return float
     */
    public function getFee(): float
    {
        return $this->fee;
    }

    /**
     * @param float $fee
     */
    public function setFee(float $fee): void
    {
        $this->fee = $fee;
    }

    public function __toString():string
    {
        return "Student[".parent::__toString().", program=".$this->program.", year=".$this->year.", fee=".$this->fee."]"; // TODO: Change the autogenerated stub
    }
}

class Staff extends Person{
    private string $school;
    private float $pay;

    public function __construct(string $name, string $address, $school, $pay)
    {
        parent::__construct($name, $address);
        $this->school = $school;
        $this->pay = $pay;
    }

    /**
     * @return string
     */
    public function getSchool(): string
    {
        return $this->school;
    }

    /**
     * @param string $school
     */
    public function setSchool(string $school): void
    {
        $this->school = $school;
    }

    /**
     * @return float
     */
    public function getPay(): float
    {
        return $this->pay;
    }

    /**
     * @param float $pay
     */
    public function setPay(float $pay): void
    {
        $this->pay = $pay;
    }

    public function __toString():string
    {
        return "Staff[".parent::__toString().", school=".$this->school.", pay=".$this->pay."]"; // TODO: Change the autogenerated stub
    }
}

$studentTest = new Student("John Doe", "USA", "PHP",2023,1000);

echo $studentTest;

echo PHP_EOL;
$staffTest = new Staff("Jenny Doe", "Canada","UOT", 3000);

echo $staffTest;

